include:
    - project: 'rpackages/r-configuration'
      file: 'gitlab-ci-Rimage-ImportsLinkingTo-template.yml'


#Test against all supported solvers and report code coverage
etxR-stable-cplex:
    image: registry.gitlab.etx.local/etherapeutics/etxdockerfiles/rimage:rcplex1271
    stage: test
    before_script:
      - R -q -e 'install.packages("slam")'
      - apt update && apt install -y glpk-utils libglpk-dev
      - wget https://cran.r-project.org/src/contrib/Rcplex_0.3-3.tar.gz
      - R CMD INSTALL --configure-args="--with-cplex-include=${CPLEX_INCLUDE_PATH} --with-cplex-cflags=-fPIC --with-cplex-lib='-L${CPLEX_LIB_PATH}/static_pic -lcplex -lm -lpthread'" Rcplex*.tar.gz
      - wget https://cran.r-project.org/src/contrib/cplexAPI_1.3.3.tar.gz
      - R CMD INSTALL --configure-args="--with-cplex-dir=${CPLEX_INCLUDE_PATH}/../" cplexAPI*.tar.gz
    script:
      - perl -p -i -e 'if($_ ~~ m/Version:/){s/(\d+\.?\d*)\.?\d*/$1\.$ENV{'CI_PIPELINE_ID'}/}' DESCRIPTION
      - R -q -e 'devtools::install_deps(".",dependencies = c("Imports","Suggests"))'
      - R CMD build .
      - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
      - R CMD check "${PKG_FILE_NAME}"
      - R -q -e 'if(any(grepl("WARNING",list.files("/builds/",pattern = "00check.log", recursive = TRUE, full.names=TRUE)))) stop("R CMD check must not report any WARNINGS in order for a build to be considered successful")'
      - export COVR_COVRIGNORE="R/heinzWrapper.R" #Not even exported. Pure utility for benchmarking
      - R -q -e 'covr::package_coverage(type="all")'
    artifacts:
      expire_in: 1 weeks
      when: always
      paths:
      - ./*.tar.gz
      - ./*.Rcheck
