# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: 
  - linux
  - osx

cache: packages

language: R
r:
  - release

apt_packages:
  - libglpk-dev
  - coinor-libcbc-dev 
  - coinor-libclp-dev
  
brew_packages:
  - glpk
  - coin-or-tools/coinor/cbc

r_packages:
  - Rglpk
  - covr  #code coverage tool  
  
r_github_packages:
  - dirkschumacher/rcbc # No CRAN version yet
  
bioc_packages:
  - lpsymphony # Builds from source

after_success:
  - test $TRAVIS_OS_NAME == "linux" && travis_wait Rscript -e 'covr::codecov()' # Only produce coverage on linux builds
  
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false # Rcplex is not available for testing
